eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    api-b:
      path: /api-view/**
      serviceId: INDEX-VIEW
    api-c:
      path: /api-person/**
      serviceId: PERSONAL-INVESTMENT-SERVER
